package psbd;

public enum PanelEnum {
    LOGIN,
    RESTOREPASSWORD,
    CREATEACCOUNT,
    CREATECLIENACCOUNT,
    CLIENTMAIN,
    CREATEORDER,
    CREATEREVIEW,
    EDITCLIENTDATA,
    EDITREVIEW,
    COOKMAIN,
    COURIERMAIN,
    ADMINMAIN,
    SUPPLIERMAIN,
    MANAGERMAIN,
    RECIPEMANAGER,
    WAREHOUSESTATS,
    DISCOUNTMANAGER,
    CREATEDELIVERY,
    EDITSTORAGE;
}
